
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://joegrundman.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /hugsar

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Hugsar"
title: "Hugsar"
description: "Website for Bristol-based band, Hugsar"
keywords: "Hugsar, Tom Grundman, Josefina Bosisio"
favicon: "/img/favicon.png"

################
# Header layout #
################

black-favicon: "/img/favicon.png"

background-img: "../img/custard-cream-sm-tile.jpg"
##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "We are HUGSAR"
  - text: "We are a band"
  - text: "We make music"





me-img: "/img/hugsar-logo-main-transp.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: False
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: False

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/hugsar-bass.png"
    date: "September 2016"
    description: "Playing at Hammersmith Arena!"
  - image: "/img/timeline/hugsar-guitar.png"
    date: " July 2016"
    description: "Gig at pub in Bristol"
  - image: "/img/timeline/hugsar-drummer.png"
    date: "June 2016"
    description: "Recording new EP"

# First image of the Timeline

timeline-img: "/img/timeline/hugsar-vocals.png"

###########
# Contact #
###########

email: "y.hugsar@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Hugsar is Bristol's most exciting new band made up of the most talented musicians"
author_blurb_image: "/img/hugsar-name-transp.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  # - title: "github"
  #   url: "https://github.com/Joegrundman/hugsar"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/hugsar-logo-orig.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

